# -*- coding: utf-8 -*-
"""QR code with python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17ukbGbES3bNIU3r9RIvlpSeTswLScoNy
"""

!pip install qrcode

#Import Library
import qrcode

#Generate QR Code
img=qrcode.make('Hello world')
img.save('hello.png')


#display the QR
import cv2
from google.colab.patches import cv2_imshow

img = cv2.imread('hello.png', cv2.IMREAD_COLOR)
cv2_imshow(img)


#Create an advanced QR code
qr = qrcode.QRCode(
    version=1,
    error_correction=qrcode.constants.ERROR_CORRECT_L,
    box_size=10,
    border=4,
)
data = { "url" :'https://www.pythonaa.com/'}
qr.add_data(data)
#qr.make(fit=True)
img = qr.make_image(fill_color="blue", back_color="white")
img.save("pythonaa.png")


#display the advanced QR
img = cv2.imread('pythonaa.png', cv2.IMREAD_COLOR)
cv2_imshow(img)



# Read data from the advanced QR code
img=cv2.imread("pythonaa.png")

det=cv2.QRCodeDetector()

val, pts, st_code = det.detectAndDecode(img)

print(val)


# Read data from the simple QR code

img=cv2.imread("hello.png")

det=cv2.QRCodeDetector()

val, pts, st_code = det.detectAndDecode(img)

print(val)